name: Unit Tests on Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Swift Setup
      uses: YOCKOW/Action-setup-swift@v1.1.0
      with:
        # Latest released version of Swift
        swift-version: 5.1.4
    - name: Test
      run: swift test
